# Generated by Django 4.1.7 on 2023-02-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoItems',
            new_name='ToDoItem',
        ),
    ]
